[browser]  # Settings for the client browser windows.
x_size = 600
y_size = 1080

[browser.proxy]  # Settings for the proxy server.
ip = ""
port = 0
is_socks = false
socks_version = 5

[redeem]
skip_proof_of_purchase = false  # DO NOT CHANGE THIS VALUE unless your script pauses for 5 seconds in the "we have a winner" section.
open_redemption_page = true     # Automatically open redemption page on your default browser with the code pre-filled.
xp_boost_only = true            # Ignore non-XP boost codes (emblem/backdrop).

[info]
country_code = "NI"           # Do not change this unless required.
phone_number = "7911 123456"  # Old number not in use.
postcode = "SW1A 1AA"         # Any North Ireland postcode should work.
store = "Other"
