[browser]  # Settings for the client browser windows.
x_size = 600
y_size = 1080

[redeem]
open_redemption_page = true  # Automatically open redemption page on your default browser with the code pre-filled.
xp_boost_only = true         # Ignore non-XP boost codes (emblem/backdrop).

[info]
country_code = "NI"           # Do not change this unless required.
phone_number = "7911 123456"  # Old number not in use.
postcode = "SW1A 1AA"         # Any North Ireland postcode should work.
store = "Other"
