[browser]  # Settings for the client browser windows.
x_size = 600
y_size = 1080

[redeem]
open_redemption_page = true  # Automatically open redemption page on your default browser with the code pre-filled.
xp_boost_only = true         # Ignore non-XP boost codes (emblem/backdrop).

[info]
country_code = "GB"            # Do not change this unless required.
bar_code = "4066"              # Any valid bar code. (4066, 0612, 0216, 4071, etc.)
phone_number = "07519 714878"  # Old number not in use.
postcode = "BD1 1AF"           # Any UK postcode should work.
store = "Tesco"